# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/baidu/Desktop/workspace/valois

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/baidu/Desktop/workspace/valois

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/baidu/Desktop/workspace/valois/CMakeFiles /Users/baidu/Desktop/workspace/valois/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/baidu/Desktop/workspace/valois/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named output/gtest_test

# Build rule for target.
output/gtest_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 output/gtest_test
.PHONY : output/gtest_test

# fast build rule for target.
output/gtest_test/fast:
	$(MAKE) -f CMakeFiles/output/gtest_test.dir/build.make CMakeFiles/output/gtest_test.dir/build
.PHONY : output/gtest_test/fast

#=============================================================================
# Target rules for targets named threadpool/output/TestThreadpool

# Build rule for target.
threadpool/output/TestThreadpool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 threadpool/output/TestThreadpool
.PHONY : threadpool/output/TestThreadpool

# fast build rule for target.
threadpool/output/TestThreadpool/fast:
	$(MAKE) -f CMakeFiles/threadpool/output/TestThreadpool.dir/build.make CMakeFiles/threadpool/output/TestThreadpool.dir/build
.PHONY : threadpool/output/TestThreadpool/fast

#=============================================================================
# Target rules for targets named mempool/output/TestMempool

# Build rule for target.
mempool/output/TestMempool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mempool/output/TestMempool
.PHONY : mempool/output/TestMempool

# fast build rule for target.
mempool/output/TestMempool/fast:
	$(MAKE) -f CMakeFiles/mempool/output/TestMempool.dir/build.make CMakeFiles/mempool/output/TestMempool.dir/build
.PHONY : mempool/output/TestMempool/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f thirdparty/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make thirdparty/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f thirdparty/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make thirdparty/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f thirdparty/googletest-build/googlemock/gtest/CMakeFiles/gtest_main.dir/build.make thirdparty/googletest-build/googlemock/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f thirdparty/googletest-build/googlemock/gtest/CMakeFiles/gtest.dir/build.make thirdparty/googletest-build/googlemock/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

mempool/example/TestMempool.o: mempool/example/TestMempool.cpp.o

.PHONY : mempool/example/TestMempool.o

# target to build an object file
mempool/example/TestMempool.cpp.o:
	$(MAKE) -f CMakeFiles/mempool/output/TestMempool.dir/build.make CMakeFiles/mempool/output/TestMempool.dir/mempool/example/TestMempool.cpp.o
.PHONY : mempool/example/TestMempool.cpp.o

mempool/example/TestMempool.i: mempool/example/TestMempool.cpp.i

.PHONY : mempool/example/TestMempool.i

# target to preprocess a source file
mempool/example/TestMempool.cpp.i:
	$(MAKE) -f CMakeFiles/mempool/output/TestMempool.dir/build.make CMakeFiles/mempool/output/TestMempool.dir/mempool/example/TestMempool.cpp.i
.PHONY : mempool/example/TestMempool.cpp.i

mempool/example/TestMempool.s: mempool/example/TestMempool.cpp.s

.PHONY : mempool/example/TestMempool.s

# target to generate assembly for a file
mempool/example/TestMempool.cpp.s:
	$(MAKE) -f CMakeFiles/mempool/output/TestMempool.dir/build.make CMakeFiles/mempool/output/TestMempool.dir/mempool/example/TestMempool.cpp.s
.PHONY : mempool/example/TestMempool.cpp.s

test/test.o: test/test.cpp.o

.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) -f CMakeFiles/output/gtest_test.dir/build.make CMakeFiles/output/gtest_test.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i

.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) -f CMakeFiles/output/gtest_test.dir/build.make CMakeFiles/output/gtest_test.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s

.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) -f CMakeFiles/output/gtest_test.dir/build.make CMakeFiles/output/gtest_test.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

test/unittest/gtest_test.o: test/unittest/gtest_test.cpp.o

.PHONY : test/unittest/gtest_test.o

# target to build an object file
test/unittest/gtest_test.cpp.o:
	$(MAKE) -f CMakeFiles/output/gtest_test.dir/build.make CMakeFiles/output/gtest_test.dir/test/unittest/gtest_test.cpp.o
.PHONY : test/unittest/gtest_test.cpp.o

test/unittest/gtest_test.i: test/unittest/gtest_test.cpp.i

.PHONY : test/unittest/gtest_test.i

# target to preprocess a source file
test/unittest/gtest_test.cpp.i:
	$(MAKE) -f CMakeFiles/output/gtest_test.dir/build.make CMakeFiles/output/gtest_test.dir/test/unittest/gtest_test.cpp.i
.PHONY : test/unittest/gtest_test.cpp.i

test/unittest/gtest_test.s: test/unittest/gtest_test.cpp.s

.PHONY : test/unittest/gtest_test.s

# target to generate assembly for a file
test/unittest/gtest_test.cpp.s:
	$(MAKE) -f CMakeFiles/output/gtest_test.dir/build.make CMakeFiles/output/gtest_test.dir/test/unittest/gtest_test.cpp.s
.PHONY : test/unittest/gtest_test.cpp.s

threadpool/example/TestThreadpool.o: threadpool/example/TestThreadpool.cpp.o

.PHONY : threadpool/example/TestThreadpool.o

# target to build an object file
threadpool/example/TestThreadpool.cpp.o:
	$(MAKE) -f CMakeFiles/threadpool/output/TestThreadpool.dir/build.make CMakeFiles/threadpool/output/TestThreadpool.dir/threadpool/example/TestThreadpool.cpp.o
.PHONY : threadpool/example/TestThreadpool.cpp.o

threadpool/example/TestThreadpool.i: threadpool/example/TestThreadpool.cpp.i

.PHONY : threadpool/example/TestThreadpool.i

# target to preprocess a source file
threadpool/example/TestThreadpool.cpp.i:
	$(MAKE) -f CMakeFiles/threadpool/output/TestThreadpool.dir/build.make CMakeFiles/threadpool/output/TestThreadpool.dir/threadpool/example/TestThreadpool.cpp.i
.PHONY : threadpool/example/TestThreadpool.cpp.i

threadpool/example/TestThreadpool.s: threadpool/example/TestThreadpool.cpp.s

.PHONY : threadpool/example/TestThreadpool.s

# target to generate assembly for a file
threadpool/example/TestThreadpool.cpp.s:
	$(MAKE) -f CMakeFiles/threadpool/output/TestThreadpool.dir/build.make CMakeFiles/threadpool/output/TestThreadpool.dir/threadpool/example/TestThreadpool.cpp.s
.PHONY : threadpool/example/TestThreadpool.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... install"
	@echo "... output/gtest_test"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... threadpool/output/TestThreadpool"
	@echo "... list_install_components"
	@echo "... mempool/output/TestMempool"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... mempool/example/TestMempool.o"
	@echo "... mempool/example/TestMempool.i"
	@echo "... mempool/example/TestMempool.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
	@echo "... test/unittest/gtest_test.o"
	@echo "... test/unittest/gtest_test.i"
	@echo "... test/unittest/gtest_test.s"
	@echo "... threadpool/example/TestThreadpool.o"
	@echo "... threadpool/example/TestThreadpool.i"
	@echo "... threadpool/example/TestThreadpool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

